### ISSUE TITLE
problems to compile calamares

### ISSUE THREAD

**Issue by wellyton-xs** [arcolinuxiso/alci-pkgbuild#2]
Hi, I'm new to developing Linux distributions and I've been struggling with the Calamares compilation and configuration process for approximately a month... I have the basics of my distro ready and lots of ideas and dreams to implement, but I'm having difficulties at this stage of creating the distro installation... This project, the ALCI was a great hope that I could have a form of guide for this process...

 to compile calamares, I believe I followed the steps correctly... I ran the script that installs the dependencies and then the script that does the build, I even found it incredible to automate the build and clean up after the process, I did the same with my process of building the ISO with archiso on my distro...

 The issue is that when compiling, even running the scripts I got the following error message:

-- Configuring done (2.8s)
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "calamares".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "libcalamarespartitiontest".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "libcalamarespartitionkpmtest".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "calamares_job_fsresizer".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "calamares_viewmodule_partition".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "partitionjobtest".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "partitionclearmountsjobtest".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "partitioncreatelayoutstest".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "partitiondevicestest".

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "partitionconfigtest".

-- Generating done (0.3s)
CMake Warning:
  Manually-specified variables were not used by the project:

    Boost_NO_BOOST_CMAKE
    WEBVIEW_FORCE_WEBKIT
    WITH_KF5DBus
    WITH_PYTHONQT

CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERRO: Uma falha ocorreu em build().
    Abortando...
Moving created files to  /home/welly/packages/tortoise-repo/x86_64/
#############################################################################################
mv: não foi possível obter estado de 'alci-calamares*pkg.tar.zst': Arquivo ou diretório inexistente
Cleaning up
#############################################################################################
deleting unnecessary folders
#############################################################################################
deleting unnecessary files
#############################################################################################
#############################################################################################
#############################################################################################

I've seen so many error messages like these that I'm starting to go crazy, but I'm more stubborn than the voices that say to give up, if it's not too much trouble, a little help is always welcome <3

**Comment by arcolinuxz** [comment]
check what we do on ArcoLinux
